theme: jekyll-theme-minimal
show_downloads: true
title: ÂµCube
description: A framework for 3D printable optomechanics
github:
  zip_url: https://github.com/mdelmans/uCube/archive/0.1.zip
  tar_url: https://github.com/mdelmans/uCube/archive/0.1.tar.gz
